server:
  port: 40100
spring:
  applicatin:
    name: u-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_study_sys?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&useUnicode=true
    username: root
    password: 123abc

  mvc:
    hiddenmethod:
      filter:
        enabled=true:redis:
  password: 123456
  port: 6379
  host: 192.168.220.120
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出Sql语句执行日志
    global-config:
      db-config:
        logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
        logic-delete-value: 1 # 逻辑已删除值(默认为 1)
        logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:com/csuft/uc/mapper/xml/*xml

